<?php 
 return 
[
    "start"=> "start",
    "Choose..."=> "Choose...",
    "Save"=> "Save",
    "here is not any think"=> "here is not any think",
    "dashboard"=> "dashboard",
    "are you sure for logout from account?"=> "are you sure for logout from account?",
    "welcome"=> "welcome",
    "test stat"=> "test stat",
    "Manage"=> "Manage",
    "با این کلید، منوی سمت راست پنل را کوچک و بزرگ کنید"=> "Use this key to zoom in and out on the right panel menu",
    "داشبورد پنل و آمار ها"=> "Dashboard panel and statistics",
    "بخش تنظیمات اصلی کلی سیستم"=> "General main system settings section",
    "ورود به صفحه ی اصلی سایت"=> "Login to the main page of the site",
    "خروج از حساب کاربری"=> "Logout",
    "Dashboard"=> "Dashboard",
    "رزومه"=> "CV",
    "مدیریت لاگ های سیستم"=> "Manage system logs",
    "دسته بندی نمونه کارها"=> "Portfolio category",
    "نمونه کارها"=> "Portfolio",
    "رویدادها"=> "events",
    "پروفایل ها"=> "Profiles",
    "توانایی ها"=> "Abilities",
    "رزومه ها"=> "Resumes",
    "منو ها"=> "Menus",
    "برگه ها"=> "sheets",
    "Profiles"=> "Profiles",
    "Create Profiles"=> "Create Profiles",
    "ID"=> "ID",
    "درپارتمان"=> "In the apartment",
    "وضعیت"=> "Condition",
    "نام"=> "name",
    "تصویر"=> "the picture",
    "زبان های برنامه نویسی"=> "programming languages",
    "سمت"=> "Side",
    "بیوگرافی"=> "Biography",
    "محتوا"=> "Content",
    "انتخاب کنید"=> "Select"
];