<?php 
 return 
[
    "start"=> "start",
    "You do not have access to this page"=> "You do not have access to this page",
    "Roles Manager"=> "Roles Manager",
    "Name"=> "Name",
    "Description"=> "Description",
    "Rule Name"=> "Rule Name",
    "Data"=> "Data",
    "Role name"=> "Role name",
    "Permissions"=> "Permissions",
    "View"=> "View",
    "Update"=> "Update",
    "Delete"=> "Delete",
    "Ok"=> "Ok",
    "Cancel"=> "Cancel",
    "Are you sure?"=> "Are you sure?",
    "Are you sure want to delete this item"=> "Are you sure want to delete this item",
    "All"=> "All",
    "Show all data"=> "Show all data",
    "Page"=> "Page",
    "Show first page data"=> "Show first page data",
    "Create new rule"=> "Create new rule",
    "Reload Grid"=> "Reload Grid",
    "* Resize table columns just like a spreadsheet by dragging the column edges."=> "* Resize table columns just like a spreadsheet by dragging the column edges.",
    "Create new [0]"=> "Create new [0]",
    "(not use)"=> "(not use)",
    "Rule not exists"=> "Rule not exists",
    "Close"=> "Close",
    "Save"=> "Save",
    "Permisstions Manager"=> "Permisstions Manager",
    "Permission name"=> "Permission name",
    "create new permission"=> "create new permission",
    "Rules Manager"=> "Rules Manager",
    "Class Name"=> "Class Name",
    "create Rule"=> "create Rule",
    "User Assignment"=> "User Assignment",
    "Assignment"=> "Assignment",
    "User ID"=> "User ID",
    "Roles"=> "Roles",
    "assign role to user"=> "assign role to user"
];