<?php 
 return 
[
    "start"=> "start",
    "login to user account"=> "login to user account",
    "please enter your account details"=> "please enter your account details",
    "login page title"=> "login page title",
    "are you sure for logout from account?"=> "are you sure for logout from account?",
    "Your email is not verified yet, please verify your email or <a href=\"#\">get new verification email<\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/a>"=> "Your email is not verified yet, please verify your email or <a href=",
    "Your email is not verified yet, please verify your email or <a href=\"#\">get new verification email<\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/a>"=> "Your email is not verified yet, please verify your email or <a href=",
    "Your email is not verified yet, please verify your email or <a href=\"#\">get new verification email<\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/a>"=> "Your email is not verified yet, please verify your email or <a href=",
    "Your email is not verified yet, please verify your email or <a href=\"#\">get new verification email<\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\/a>"=> "Your email is not verified yet, please verify your email or <a href=",
    "Your email is not verified yet, please verify your email"=> "Your email is not verified yet, please verify your email",
    "active account"=> "active account",
    "forgot password"=> "forgot password",
    "Login with mobile number"=> "Login with mobile number",
    "please inter mobile number with country format, eg: +989121234567"=> "please inter mobile number with country format, eg: +989121234567",
    "please enter mobile number with country format, eg: +989121234567"=> "please enter mobile number with country format, eg: +989121234567",
    "Incorrect username or password."=> "Incorrect username or password.",
    "Login with email address"=> "Login with email address",
    "signup"=> "signup",
    "recover user account"=> "recover user account",
    "email"=> "email",
    "password"=> "password",
    "Remember Me"=> "Remember Me",
    "mobile"=> "mobile",
    "please select your recovery method"=> "please select your recovery method",
    "recovery account with email address"=> "recovery account with email address",
    "recovery account with sms on your phone"=> "recovery account with sms on your phone",
    "back"=> "back",
    "back to login"=> "back to login",
    "recovery account"=> "recovery account",
    "send code"=> "send code",
    "hello \n your verification code for siteconfig.ir is [0]"=> "hello  your verification code for siteconfig.ir is [0]",
    "sms system is under debug mode"=> "sms system is under debug mode",
    "send sms is now disable, try few minutes again"=> "send sms is now disable, try few minutes again",
    "validate account"=> "validate account",
    "please enter code that sent to your phone"=> "please enter code that sent to your phone",
    "mobile_code"=> "mobile_code",
    "verification code"=> "verification code",
    "please enter your account email"=> "please enter your account email",
    "reset password"=> "reset password",
    "please enter new password for your account"=> "please enter new password for your account",
    "enter new password"=> "enter new password",
    "confirm password"=> "confirm password",
    "your password length must between 6 to 70"=> "your password length must between 6 to 70",
    "you must enter at least one digit"=> "you must enter at least one digit",
    "you must enter at least one lowercase char"=> "you must enter at least one lowercase char",
    "you must enter at least one uppercase char"=> "you must enter at least one uppercase char",
    "you must enter at least one symbol"=> "you must enter at least one symbol",
    "this form is invalid"=> "this form is invalid",
    "\r\npassword must has : \n\r\nat least one lowercase char \n\r\nat least one uppercase char \n\r\nat least one digit \n\r\nat least one special sign of ! @ # $ %\r\n\t\t\t"=> "password must has : at least one lowercase char at least one uppercase char at least one digit at least one special sign of ! @ # $ %\t\t\t",
    "\r\npassword must has : <br>\r\nat least one lowercase char <br>\r\nat least one uppercase char <br>\r\nat least one digit <br>\r\nat least one special sign of ! @ # $ %\r\n\t\t\t"=> "password must has : <br>at least one lowercase char <br>at least one uppercase char <br>at least one digit <br>at least one special sign of ! @ # $ %\t\t\t",
    "recover account"=> "recover account",
    "submit"=> "submit",
    "account recovery - test"=> "account recovery - test",
    "We've sent you an email"=> "We've sent you an email",
    "Please close this page and refer to your email"=> "Please close this page and refer to your email",
    "this page does not exist"=> "this page does not exist",
    "Your account password changed"=> "Your account password changed",
    "Hi [user]"=> "Hi [user]",
    "Your account password changed in [time] <br>\r\nclient detail: <br>\r\nIP: [ip]\r\nOS Name: [device]\r\nAgent Name: [agent]\r\n"=> "Your account password changed in [time] <br>client detail: <br>IP: [ip]OS Name: [device]Agent Name: [agent]",
    "Your account password changed in [time] <br>\r\nclient detail: <br>\r\nIP: [ip] <br>\r\nOS Name: [device] <br>\r\nAgent Name: [agent] <br>\r\n"=> "Your account password changed in [time] <br>client detail: <br>IP: [ip] <br>OS Name: [device] <br>Agent Name: [agent] <br>",
    "account updated - test"=> "account updated - test",
    "create new account"=> "create new account",
    "Login"=> "Login",
    "this mobile number is exist"=> "this mobile number is exist",
    "This mobile number is already registered, if you entered the number correctly, see the account login page."=> "This mobile number is already registered, if you entered the number correctly, see the account login page.",
    "your keyboard language must be latin"=> "your keyboard language must be latin",
    "Please select your country flag, then enter your mobile number like example"=> "Please select your country flag, then enter your mobile number like example",
    "enter email name"=> "enter email name",
    "this email registered on system, please enter another email address"=> "this email registered on system, please enter another email address",
    "your input text is not valid email address"=> "your input text is not valid email address",
    "Please enter your email address to stay updated and receive notifications. "=> "Please enter your email address to stay updated and receive notifications. "
];