<?php 
 return 
[
    "start"=> "start",
    "Dashboard"=> "Dashboard",
    "User Manage"=> "User Manage",
    "Manage Users"=> "Manage Users",
    "Menus"=> "Menus",
    "Services"=> "Services",
    "Contact Inbox"=> "Contact Inbox",
    "Testimotionals"=> "Testimotionals",
    "Pages"=> "Pages",
    "Articles"=> "Articles",
    "Article Comments"=> "Article Comments",
    "poll"=> "poll",
    "bots"=> "bots",
    "tornoment"=> "tornoment",
    "sites"=> "sites",
    "بخش محتوایی ربات"=> "بخش محتوایی ربات",
    "دسته بندی محتوایی"=> "دسته بندی محتوایی",
    "محتواهای ربات"=> "محتواهای ربات",
    "داشبرد"=> "داشبرد",
    "وبلاگ"=> "وبلاگ",
    "نوشته ها"=> "نوشته ها",
    "دسته ها"=> "دسته ها",
    "دیدگاه ها"=> "دیدگاه ها",
    "فرم ها"=> "فرم ها",
    "سیستم"=> "سیستم",
    "زبان"=> "زبان",
    "منو"=> "منو",
    "سئو"=> "سئو",
    "کاربران مدیر"=> "کاربران مدیر",
    "ویجت ها"=> "ویجت ها",
    "صفحات"=> "صفحات",
    "صفحه جدید"=> "صفحه جدید",
    "همه ی صفحات"=> "همه ی صفحات",
    "فروشگاه"=> "فروشگاه",
    "محصولات"=> "محصولات",
    "گروه محصولات"=> "گروه محصولات"
];