<?php 
 return 
[
    "start"=> "start",
    "You do not have access to this page"=> "شما مجوز دسترسی به این صفحه را ندارید",
    "Roles Manager"=> "مدیریت نقش ها",
    "Name"=> "نام",
    "Description"=> "توضیحات",
    "Rule Name"=> "نام نقش",
    "Data"=> "Data",
    "Role name"=> "نام نقش",
    "Permissions"=> "مجوز ها",
    "View"=> "نمایش",
    "Update"=> "بروزرسانی",
    "Delete"=> "حذف",
    "Ok"=> "تایید",
    "Cancel"=> "لغو",
    "Are you sure?"=> "اطمینان دارید؟",
    "Are you sure want to delete this item"=> "برای حذف این مورد اطمینان کافی دارید؟",
    "All"=> "همه",
    "Show all data"=> "نمایش همه ی اطلاعات",
    "Page"=> "صفحه",
    "Show first page data"=> "Show first page data",
    "Create new rule"=> "ایجاد نقش جدید",
    "Reload Grid"=> "بازنشانی جدول",
    "* Resize table columns just like a spreadsheet by dragging the column edges."=> "* برای تغییر اندازه ی ستون ها، کافیست لبه ی ستون ها را با ماوس جابجا کنید",
    "Create new [0]"=> "Create new [0]",
    "(not use)"=> "(استفاده نشده)",
    "Rule not exists"=> "نقش موجود نیست",
    "Close"=> "بستن",
    "Save"=> "ذخیره",
    "Permisstions Manager"=> "مدیریت دسترسی ها",
    "Permission name"=> "نام دسترسی",
    "create new permission"=> "ایجاد دسترسی جدید",
    "Rules Manager"=> "مدیریت نقش ها",
    "Class Name"=> "نام کلاس php",
    "create Rule"=> "ثبت نقش جدید",
    "User Assignment"=> "اختصاص نقش به کاربر",
    "Assignment"=> "واگذاری",
    "User ID"=> "شناسه ی کاربری",
    "Roles"=> "نقش ها",
    "assign role to user"=> "تخصیص نقش به کاربر"
];