<?php 
 return 
[
    "start"=> "start",
    "New User"=> "کاربر جدید",
    "Add New User"=> "افزودن کاربر جدید",
    "Site Users"=> "کاربران سایت",
    "fullname"=> "نام و نام خانوادگی کاربر",
    "email"=> "ایمیل",
    "image"=> "تصویر",
    "status"=> "وضعیت",
    "password"=> "رمز عبور",
    "mobile_verification_code"=> "کد اعتبار سنجی موبایل",
    "email_verification_hash"=> "کد اعتبار سنجی ایمیل",
    "verified_mobile"=> "وضعیت وریفای موبایل",
    "verified_email"=> "وضعیت وریفای ایمیل",
    "user not verified email"=> "کاربر ایمیل خود را تایید نکرده است",
    "user not verified mobile"=> "کاربر موبایل خود را تایید نکرده است",
    "mobile"=> "تلفن همراه",
    "If Empty, Password Will Set To 123456"=> "اگر این فیلد خالی باشد، رمز به 123456 تغییر میکند",
    "credit"=> "میزان شارژ کاربر",
    "credit:"=> "شارژ کاربری:",
    "Image"=> "تصاویر",
    "Status Users"=> "وضعیت کاربر",
    "Manage Users"=> "Manage Users",
    "user index"=> "user index",
    "add site user"=> "add site user",
    "add another site user"=> "add another site user",
    "Manage Users Index"=> "Manage Users Index",
    "index"=> "index",
    "hash"=> "hash"
];