<?php


namespace system\assets\fonts;


use YiiMan\YiiBasics\lib\AssetBundle;
use YiiMan\YiiBasics\lib\i18n\Layout;

class FontsAssets extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = realpath(__DIR__ . '/files');
//        $layout = Layout::run();
//        if ($layout == 'rtl') {
            $this->css[] = 'css/fonts.css';
//        }
    }
}
